<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LWhisper.Core\LWhisper.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Whisper.net" Version="1.9.0" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.9.0" />
    <PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.9.0" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

</Project>
